### ISSUE TITLE
Install expo and other libraries

### ISSUE THREAD

**Issue by KarolRechman** [Myfirstgitrep19/Icespotting#6]
Install expo and other libraries

**Comment by Myfirstgitrep19** [comment]
Installed dependencies:
 "@react-navigation/bottom-tabs": "^5.11.11",
"expo": "~41.0.1",
"expo-camera": "~11.0.2",
"expo-status-bar": "~1.0.4"
"firebase": "8.2.3"
"react-native-maps": "0.27.1"
"react-native-paper": "^4.9.1"
